### ISSUE TITLE
HTTP Basic Authentication

### ISSUE THREAD

**Issue by jonathanlaniado** [edualm/SeedTruck#11]
Hey, I use HTTP basic authentication for my Transmission RPC. I _do not_ use the built-in Transmission authentication.

Universally access to my client is: `https://username:password@domain.com`. I tried using that as the endpoint, while leaving username and password blank in SeedTruck, but it errors out.

Is this something that is supported, and if not, can it? :)

**Comment by edualm** [comment]
Hey,

It doesn't have explicit support, but to be honest, it _should_ work, as the normal Transmission authentication is HTTP basic with some bells and whistles.

I'll run some tests as soon as I have some time :)

**Comment by jonathanlaniado** [comment]
Thanks, that would be great. I tried inputting it in many different ways, but it doesn't budge. Keep me posted if you get any progress/insight on this! :)

**Comment by edualm** [comment]
Hey @jonathanlaniado,

I've done some tests and it __should__ actually be working.

Can you tell me how you are inputting the server URL? The path for RPC is required - for example, it should be something like `https://domain.com:port/transmission/rpc`.

If you try it like that, does it work?

**Comment by jonathanlaniado** [comment]
Nailed it, thank you. I was missing `/transmission/rpc`. Apologies if I overlooked that in the docs, thank you!

**Comment by edualm** [comment]
No need to apologize, I should make that clearer in the app. Glad it's working now! :)
