### ISSUE TITLE
Not able to connect the server

### ISSUE THREAD

**Issue by Jue-Xu** [edualm/SeedTruck#13]
Hi, thanks for your effort for developing this app. I have trouble in connecting to my Transmission server under my local network:
![IMG_DA3929CCBEB1-1](https://user-images.githubusercontent.com/16731479/172038320-c21224c6-9ed4-42d4-ad4e-06abf0d95ee1.jpeg)
I can successfully connect to the Transmission via webUI on Chrome (Mac and iPhone)
<img width="637" alt="image" src="https://user-images.githubusercontent.com/16731479/172038337-b73e83c4-c9dd-436c-95d7-ab0e2e89928c.png">
I tried to check the log in Xcode, but there is no output
<img width="438" alt="image" src="https://user-images.githubusercontent.com/16731479/172038413-c161a455-25d2-424d-9a34-8a0d37145fa5.png">

**Comment by gotzlotz** [comment]
Try....

(http://10.0.0.3:9091/transmission/rpc)

**Comment by Jue-Xu** [comment]
It works! Thank you!

**Comment by Jue-Xu** [comment]
It works! Thank you!

Best,
Jue
