### ISSUE TITLE
Apple Watch

### ISSUE THREAD

**Issue by gotzlotz** [edualm/SeedTruck#7]
I don’t have certs for my Apple Watch so I need to use a 7 day cert with my Apple ID. Problem is I’m get a error about the teams. How do I remove your team?

**Comment by edualm** [comment]
What's the error you are getting? I don't use 7-day certs but I will still try to give you a hand.

**Comment by gotzlotz** [comment]
Sorry for the long delay. The errors I get is “WatchConnectivity session on paired device is not reachable”
 
Also I can’t open torrent from the app or from the files app unless I use the share sheet.

Lastly you think you can add a speed limit button?

**Comment by edualm** [comment]
Sorry for the super late (almost half a year after!) delay.

 - The connectivity issues should be fixed.
 - As for the share sheet, I think that has to do with the mime type of downloaded files. I've noticed that some files I download automatically get opened on Seed Truck, and others exhibit the behavior you described. I am afraid I don't have a fix for that as of now though.
 - The speed limit could be done I think. I'll add that on the next release.

**Comment by edualm** [comment]
Closing as questions were answered, missing issue is being tracked on https://github.com/edualm/SeedTruck/issues/9.
